config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root 'users#index'

  resources :rewards
  resources :groups
  resources :transactions
  resources :users

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post '/slack', to: 'slack#index'
      post '/slack_redeem', to: 'slack#redeem'
      get  '/slack_photo', to: 'slack#photo'
      post '/admin', to: 'admin#give'
    end
  end

  match '/health_check', to: 'application#health_check', via: [:get, :head]
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :transactions

  INFINITE_STOCK = 10000

  scope :available, -> { where(visible: true).where('stock_count > 0').order(id: :asc) }

  def self.default_scope
    order(id: :asc)
  end

  def self.plaintext_list
    Reward.where(visible: true).where('stock_count > 0').all.collect do |r|
      if r.stock_count == Reward::INFINITE_STOCK
        I18n.t('slack.reward.line_item', id:r.id, name:r.name, cost:r.cost)
      else
        I18n.t('slack.reward.line_item_stock_count', id:r.id, name:r.name, cost:r.cost, stock:r.stock_count)
      end
    end.join("\n")
  end

  def redeem_for(user:)
    if user.balance >= self.cost
      user.balance -= self.cost
      self.stock_count -= 1 unless self.stock_count == INFINITE_STOCK
      txn = Transaction.new(sender: user, recipient: user, message: self.name, amount: self.cost, reward: self, transaction_type: Transaction.transaction_types[:redemption])
      ActiveRecord::Base.transaction do
        self.save!
        user.save!
        txn.save!
      end
    else
      return false
    end
  rescue ActiveRecord::RecordInvalid => exception
    p exception.message
    return false
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # GET /rewards
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  def create
    @reward = Reward.new(reward_params)

    if @reward.save
      redirect_to @reward, notice: 'Reward was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rewards/1
  def update
    if @reward.update(reward_params)
      redirect_to @reward, notice: 'Reward was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rewards/1
  def destroy
    @reward.destroy
    redirect_to rewards_url, notice: 'Reward was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit(:name, :image, :cost, :stock_count, :visible)
    end
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward, local: true) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reward_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :reward_image %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost, id: :reward_cost %>
  </div>

  <div class="field">
    <%= form.label :stock_count %>
    <%= form.number_field :stock_count, id: :reward_stock_count %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible, id: :reward_visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.haml
%p#notice= notice

.container
  .row
    .col
      %h1 Rewards
    .col.text-right
      = link_to new_reward_path do
        .btn.btn-primary Add new Rewards

%table.table.table-striped
  %thead
    %tr
      %th
      %th ID
      %th Name
      %th Cost
      %th Stock
      %th Redeemed
      %th Visible
      %th{:colspan => "3"}
  %tbody
    - @rewards.each do |reward|
      %tr
        %td= reward.image_url
        %td= reward.id
        %td= reward.name
        %td= reward.cost
        %td= reward.stock_count
        %td= reward.transactions.count
        %td= reward.visible
        / %td= link_to 'Show', reward
        %td= link_to 'Edit', edit_reward_path(reward)

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reward.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @reward.image_url %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @reward.cost %>
</p>

<p>
  <strong>Stock count:</strong>
  <%= @reward.stock_count %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @reward.visible %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>